"""Hyperparameter configurations for all 30 experiments.

10 configurations per algorithm, each varying 1-2 parameters from a baseline.
"""

# Total training timesteps for SB3 algorithms
TOTAL_TIMESTEPS = 500_000
EVAL_FREQ = 10_000
N_EVAL_EPISODES = 5

# REINFORCE training episodes
REINFORCE_EPISODES = 5000

# ============================================================
# DQN Configurations (10 runs)
# Baseline: lr=1e-4, buffer=100K, batch=64, tau=1.0, gamma=0.99,
#           explore_frac=0.3, explore_final=0.05, net=[256,256]
# ============================================================
DQN_CONFIGS = [
    {   # Run 0: Baseline
        "name": "dqn_baseline",
        "learning_rate": 1e-4,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 1: Smaller network
        "name": "dqn_small_net",
        "learning_rate": 1e-4,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [128, 128]},
    },
    {   # Run 2: Higher learning rate
        "name": "dqn_high_lr",
        "learning_rate": 5e-4,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 3: Lower learning rate
        "name": "dqn_low_lr",
        "learning_rate": 1e-5,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 4: Larger buffer + batch
        "name": "dqn_large_buffer",
        "learning_rate": 1e-4,
        "buffer_size": 500_000,
        "batch_size": 128,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.5,
        "exploration_final_eps": 0.02,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 5: Soft update (Polyak)
        "name": "dqn_soft_update",
        "learning_rate": 1e-4,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 0.005,
        "gamma": 0.99,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 6: Lower gamma
        "name": "dqn_low_gamma",
        "learning_rate": 1e-4,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 1.0,
        "gamma": 0.95,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 7: Deeper network
        "name": "dqn_deep_net",
        "learning_rate": 1e-4,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256, 128]},
    },
    {   # Run 8: Medium lr + larger batch
        "name": "dqn_med_lr_batch",
        "learning_rate": 3e-4,
        "buffer_size": 200_000,
        "batch_size": 256,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.05,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 9: Extended exploration
        "name": "dqn_long_explore",
        "learning_rate": 1e-4,
        "buffer_size": 100_000,
        "batch_size": 64,
        "tau": 1.0,
        "gamma": 0.99,
        "exploration_fraction": 0.7,
        "exploration_final_eps": 0.01,
        "learning_starts": 5000,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
]

# ============================================================
# PPO Configurations (10 runs)
# Baseline: lr=3e-4, n_steps=2048, batch=64, n_epochs=10,
#           clip=0.2, ent=0.01, gamma=0.99, net=[256,256]
# ============================================================
PPO_CONFIGS = [
    {   # Run 0: Baseline
        "name": "ppo_baseline",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 1: Higher entropy
        "name": "ppo_high_entropy",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.2,
        "ent_coef": 0.05,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 2: Lower learning rate
        "name": "ppo_low_lr",
        "learning_rate": 1e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 3: Tighter clipping
        "name": "ppo_tight_clip",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.1,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 4: Wider clipping
        "name": "ppo_wide_clip",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.3,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 5: More epochs
        "name": "ppo_more_epochs",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 20,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 6: Smaller network
        "name": "ppo_small_net",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [128, 128]},
    },
    {   # Run 7: Larger rollout + batch
        "name": "ppo_large_rollout",
        "learning_rate": 3e-4,
        "n_steps": 4096,
        "batch_size": 128,
        "n_epochs": 10,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 8: Lower gamma
        "name": "ppo_low_gamma",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.95,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256]},
    },
    {   # Run 9: Higher lr + deeper network
        "name": "ppo_high_lr_deep",
        "learning_rate": 5e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "n_epochs": 10,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "max_grad_norm": 0.5,
        "policy_kwargs": {"net_arch": [256, 256, 128]},
    },
]

# ============================================================
# REINFORCE Configurations (10 runs)
# Baseline: lr=1e-3, gamma=0.99, hidden=[128,64], baseline=mean
# ============================================================
REINFORCE_CONFIGS = [
    {   # Run 0: Baseline
        "name": "reinforce_baseline",
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "hidden_sizes": [128, 64],
        "baseline": "mean",
    },
    {   # Run 1: No baseline
        "name": "reinforce_no_baseline",
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "hidden_sizes": [128, 64],
        "baseline": "none",
    },
    {   # Run 2: Lower learning rate
        "name": "reinforce_low_lr",
        "learning_rate": 1e-4,
        "gamma": 0.99,
        "hidden_sizes": [128, 64],
        "baseline": "mean",
    },
    {   # Run 3: Higher learning rate
        "name": "reinforce_high_lr",
        "learning_rate": 5e-3,
        "gamma": 0.99,
        "hidden_sizes": [128, 64],
        "baseline": "mean",
    },
    {   # Run 4: Larger network
        "name": "reinforce_large_net",
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "hidden_sizes": [256, 128],
        "baseline": "mean",
    },
    {   # Run 5: Smaller network
        "name": "reinforce_small_net",
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "hidden_sizes": [64, 32],
        "baseline": "mean",
    },
    {   # Run 6: Lower gamma
        "name": "reinforce_low_gamma",
        "learning_rate": 1e-3,
        "gamma": 0.95,
        "hidden_sizes": [128, 64],
        "baseline": "mean",
    },
    {   # Run 7: Very low gamma
        "name": "reinforce_very_low_gamma",
        "learning_rate": 1e-3,
        "gamma": 0.90,
        "hidden_sizes": [128, 64],
        "baseline": "mean",
    },
    {   # Run 8: Deeper network
        "name": "reinforce_deep_net",
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "hidden_sizes": [256, 128, 64],
        "baseline": "mean",
    },
    {   # Run 9: Running baseline
        "name": "reinforce_running_baseline",
        "learning_rate": 3e-4,
        "gamma": 0.99,
        "hidden_sizes": [128, 64],
        "baseline": "running",
    },
]
